name: web3_transaction_codec
description: This is a transaction codec for blockchain transactions
version: 0.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  convert: ^3.0.1
  flutter:
    sdk: flutter
  http:
  pointycastle: ^3.6.0
  typed_data: ^1.3.0
  web3dart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
